const actionTypes = {
  START_DESKTOP_APP: '__START_DESKTOP_APP',
  START_MOBILE_APP: '__START_MOBILE_APP',
  CHANGE_HISTORY: '__CHANGE_HISTORY',

  FETCH_ACCOUNTS: '__FETCH_ACCOUNTS',
};

export default actionTypes;
