const actionTypes = {
  START_DESKTOP_APP: '__START_DESKTOP_APP',
  START_MOBILE_APP: '__START_MOBILE_APP',
  CHANGE_HISTORY: '__CHANGE_HISTORY',

  FETCH_ACCOUNTS: '__FETCH_ACCOUNTS',
  UPDATE_ACCOUNT: '__UPDATE_ACCOUNT',
  FAIL_TO_UPDATE_ACCOUNT: '__FAIL_TO_UPDATE_ACCOUNT',
};

export default actionTypes;
